package com.maxpilotto.krand

import com.maxpilotto.krand.generators.*
import com.maxpilotto.krand.generators.DiceGenerator
import com.maxpilotto.krand.generators.EvenNumberGenerator
import com.maxpilotto.krand.generators.OddNumberGenerator
import org.junit.jupiter.api.Test

class AllTest {
    @Test
    fun one() {
//        println(FalsyGenerator().one())
        println(AMPMGenerator().one())
        println(AddressGenerator().one())
        println(AgeGenerator().one())
        println(AltitudeGenerator().one())
        println(AndroidIDGenerator().one())
        println(AnimalGenerator().one())
        println(AppleTokenGenerator().one())
        println(AreacodeGenerator().one())
        println(AvatarGenerator().one())
        println(BirthdayGenerator().one())
        println(BlackBerryPINGenerator().one())
        println(BoolGenerator().one())
        println(CFGenerator().one())
        println(CPFGenerator().one())
        println(CharacterGenerator().one())
        println(CityGenerator().one())
        println(CoinGenerator().one())
        println(ColorGenerator().one())
        println(CompanyGenerator().one())
        println(CoordinatesGenerator().one())
        println(CountryGenerator().one())
        println(CreditCardExpiryGenerator().one())
        println(CreditCardExpiryMonthGenerator().one())
        println(CreditCardExpiryYearGenerator().one())
        println(CreditCardNumberGenerator().one())
        println(CreditCardTypeGenerator().one())
        println(CurrencyGenerator().one())
        println(CurrencyPairGenerator().one())
        println(D100Generator().one())
        println(D10Generator().one())
        println(D12Generator().one())
        println(D20Generator().one())
        println(D30Generator().one())
        println(D4Generator().one())
        println(D6Generator().one())
        println(D8Generator().one())
        println(DateGenerator().one())
        println(DepthGenerator().one())
        println(DollarGenerator().one())
        println(DomainGenerator().one())
        println(EmailGenerator().one())
        println(EuroGenerator().one())
        println(FacebookIDGenerator().one())
        println(FirstnameGenerator().one())
        println(DecimalGenerator().one())
        println(GUIDGenerator().one())
        println(GenderGenerator().one())
        println(GeohashGenerator().one())
        println(GoogleAnalyticsGenerator().one())
        println(HammertimeGenerator().one())
        println(HashGenerator().one())
        println(HashtagGenerator().one())
        println(HourGenerator().one())
        println(IPGenerator().one())
        println(IPV6Generator().one())
        println(IntegerGenerator().one())
        println(KloutScoreGenerator().one())
        println(LastnameGenerator().one())
        println(LatitudeGenerator().one())
        println(LetterGenerator().one())
        println(LocaleGenerator().one())
        println(LongitudeGenerator().one())
        println(MillisecondGenerator().one())
        println(MinuteGenerator().one())
        println(MonthGenerator().one())
        println(NameGenerator().one())
        println(NaturalGenerator().one())
        println(NormalGenerator().one())
        println(ParagraphGenerator().one())
        println(PhoneGenerator().one())
        println(PostalGenerator().one())
        println(PostcodeGenerator().one())
        println(PrefixGenerator().one())
        println(PrimeGenerator().one())
        println(ProfessionGenerator().one())
        println(ProvinceGenerator().one())
        println(RadioCallSignGenerator().one())
        println(SSNGenerator().one())
        println(SecondGenerator().one())
        println(SentenceGenerator().one())
        println(StateGenerator().one())
        println(StreetGenerator().one())
        println(StringGenerator().one())
        println(SuffixGenerator().one())
        println(SyllableGenerator().one())
        println(TimestampGenerator().one())
        println(TimezoneGenerator().one())
        println(TopLevelDomainGenerator().one())
        println(TwitterGenerator().one())
        println(URLGenerator().one())
        println(WeekdayGenerator().one())
        println(WindowsPhone7ANIDGenerator().one())
//        println(WindowsPhone8ANID2Generator().one())  // Doesn't work
        println(WordGenerator().one())
        println(YearGenerator().one())
        println(ZipCodeGenerator().one())
        println(DiceGenerator().rolls(2).max(6).one())
        println(EvenNumberGenerator().one())
        println(OddNumberGenerator().one())
    }
}